sonar.sources=app, crypto, storage, main.cpp
sonar.tests=tests
sonar.test.inclusions=**/*.cpp,**/*.hpp
sonar.exclusions=build/**,vcpkg/**,**/catch.hpp,**/catch2.hpp
sonar.cfamily.compile-commands=build/compile_commands.json