name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      # -------------------------
      # Checkout repository
      # -------------------------
      - name: Checkout repo
        uses: actions/checkout@v4

      # -------------------------
      # Setup vcpkg
      # -------------------------
      - name: Setup vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git %VCPKG_ROOT%
          cd %VCPKG_ROOT%
          bootstrap-vcpkg.bat

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install libsodium
        shell: cmd
        run: |
          %VCPKG_ROOT%\vcpkg install libsodium:x64-windows

      # -------------------------
      # Configure CMake
      # -------------------------
      - name: Configure CMake
        run: |
          cmake -S . -B build ^
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake ^
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ^
            -DVCPKG_TARGET_TRIPLET=x64-windows

      # -------------------------
      # Build project
      # -------------------------
      - name: Build
        shell: cmd
        run: |
          cmake --build build --config Debug

      # -------------------------
      # Run tests
      # -------------------------
      - name: Run tests
        shell: cmd
        run: |
          ctest --test-dir build -C Debug --output-on-failure

      # -------------------------
      # SonarCloud SAST
      # -------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=tonihoooo_COMP.SEC.300
            -Dsonar.organization=tonihoooo
            -Dsonar.host.url=https://sonarcloud.io 