name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    defaults:
      run:
        shell: pwsh

    steps:
      # -------------------------
      # Checkout 
      # -------------------------
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # Setup vcpkg
      # -------------------------
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
          & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"

      # -------------------------
      # Install dependencies
      # -------------------------
      - name: Install dependencies
        run: |
          & "$env:VCPKG_ROOT\vcpkg" install libsodium:x64-windows

      # -------------------------
      # Configure CMake
      # -------------------------
      - name: Configure CMake
        run: |
          cmake -S . -B build `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON `
            -DVCPKG_TARGET_TRIPLET=x64-windows

      # -------------------------
      # Build
      # -------------------------
      - name: Build
        run: |
          cmake --build build --config Debug

      # -------------------------
      # Verify compile database exists
      # -------------------------
      - name: Check compile_commands.json
        run: |
          Get-Content build\compile_commands.json | Select-Object -First 5

      # -------------------------
      # SonarCloud Scan
      # -------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=tonihoooo_COMP.SEC.300
            -Dsonar.organization=tonihoooo
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cfamily.compile-commands=build/compile_commands.json
            -Dsonar.sources=app,crypto,storage